### ISSUE TITLE
PA Review: Continuous Play

### ISSUE THREAD

**Issue by Ian-MacLeod** [Ian-MacLeod/sound-macleod#5]
- [x] Tracks can play without errors
- [x] Tracks continue to play when navigating through app

**Comment by anastassia-b** [comment]
Awesome work! The songs do play continuously. Yesterday you showed me your implementation of the queue and we discussed it. I love the functionality-- I can add to and drag songs in the queue. It's a little tricky if you allow users to hit play on the song item in the queue... it doesn't necessarily change the queue order. Maybe I wouldn't allow users to click the play button on a song item in the queue. 

Also, you might want to delete the test track I uploaded, since it's not an mp3 file and doesn't play. You mentioned wanting to add some more functionality to the playing bar, but otherwise, this MVP is complete!
